name = "TruncatedMVN"
uuid = "502039d7-87d7-456d-8cc8-96307cceeee2"
authors = ["Eliassj <elias.sjolin@gmail.com> and contributors"]
version = "1.0.3"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Transducers = "28d57a85-8fef-5791-bfe6-a80928e7c999"

[compat]
DocStringExtensions = "0.9.4"
NonlinearSolve = "3,4"
SpecialFunctions = "2"
StaticArrays = "1"
Transducers = "0.4.84"
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
