name = "TruncatedMVN"
uuid = "502039d7-87d7-456d-8cc8-96307cceeee2"
authors = ["Eliassj <elias.sjolin@gmail.com> and contributors"]
version = "1.0.1"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
NonlinearSolve = "4"
SpecialFunctions = "2"
StaticArrays = "1"
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
